#
#define U_INSTRUCTION(n, oc)         { #n, 1, 'U', #oc},
#define J_INSTRUCTION(n, oc)         { #n, 1, 'J', #oc},
#define I_INSTRUCTION(n, oc, f3)     { #n, 2, 'I', #oc, f3},
#define B_INSTRUCTION(n, oc, f3)     { #n, 2, 'B', #oc, f3},
#define S_INSTRUCTION(n, oc, f3)     { #n, 2, 'S', #oc, f3},
#define R_INSTRUCTION(n, oc, f3, f7) { #n, 3, 'R', #oc, f3, f7},

U_INSTRUCTION(LUI,   OP_LUI)
U_INSTRUCTION(AUIPC, OP_AUIPC)

J_INSTRUCTION(JAL,   OP_JAL)

I_INSTRUCTION(JALR,  OP_JALR, 0x00)

B_INSTRUCTION(BEQ,   OP_BRANCH, 0x00)
B_INSTRUCTION(BNE,   OP_BRANCH, 0x01)
B_INSTRUCTION(BLT,   OP_BRANCH, 0x04)
B_INSTRUCTION(BGE,   OP_BRANCH, 0x05)
B_INSTRUCTION(BLTU,  OP_BRANCH, 0x06)
B_INSTRUCTION(BGEU,  OP_BRANCH, 0x07)

I_INSTRUCTION(LB,    OP_LOAD, 0x00)
I_INSTRUCTION(LH,    OP_LOAD, 0x01)
I_INSTRUCTION(LW,    OP_LOAD, 0x02)
I_INSTRUCTION(LBU,   OP_LOAD, 0x04)
I_INSTRUCTION(LHU,   OP_LOAD, 0x05)

S_INSTRUCTION(SB,    OP_STORE, 0x00)
S_INSTRUCTION(SH,    OP_STORE, 0x01)
S_INSTRUCTION(SW,    OP_STORE, 0x02)

I_INSTRUCTION(ADDI,  OP_ALUI, 0x00)
I_INSTRUCTION(SLTI,  OP_ALUI, 0x02)
I_INSTRUCTION(STLIU, OP_ALUI, 0x03)
I_INSTRUCTION(XORI,  OP_ALUI, 0x04)
I_INSTRUCTION(ORI,   OP_ALUI, 0x06)
I_INSTRUCTION(ANDI,  OP_ALUI, 0x07)

R_INSTRUCTION(SLLI,  OP_ALUI, 0x01, 0x00)
R_INSTRUCTION(SRLI,  OP_ALUI, 0x05, 0x00)
R_INSTRUCTION(SRAI,  OP_ALUI, 0x05, 0x20)

R_INSTRUCTION(ADD,   OP_ALUR, 0x00, 0x00)
R_INSTRUCTION(SUB,   OP_ALUR, 0x00, 0x20)
R_INSTRUCTION(SLL,   OP_ALUR, 0x01, 0x00)
R_INSTRUCTION(SLT,   OP_ALUR, 0x02, 0x00)
R_INSTRUCTION(SLTU,  OP_ALUR, 0x03, 0x00)
R_INSTRUCTION(XOR,   OP_ALUR, 0x04, 0x00)
R_INSTRUCTION(SRL,   OP_ALUR, 0x05, 0x00)
R_INSTRUCTION(SRA,   OP_ALUR, 0x05, 0x20)
R_INSTRUCTION(OR,    OP_ALUR, 0x06, 0x00)
R_INSTRUCTION(AND,   OP_ALUR, 0x07, 0x00)

I_INSTRUCTION(FENCE,   OP_FENCE, 0x00)
I_INSTRUCTION(FENCE.I, OP_FENCE, 0x01)

/*
 * ECALL and EBREAK are the same insttruction, just with a different immediate.
 * Let's call this the ESYS instruction.
 */

I_INSTRUCTION(ESYS,   OP_SYS, 0x00)

I_INSTRUCTION(CSRRW,  OP_SYS, 0x01)
I_INSTRUCTION(CSRRS,  OP_SYS, 0x02)
I_INSTRUCTION(CSRRC,  OP_SYS, 0x03)
I_INSTRUCTION(CSRRWI, OP_SYS, 0x05)
I_INSTRUCTION(CSRRSI, OP_SYS, 0x06)
I_INSTRUCTION(CSRRCI, OP_SYS, 0x07)

